import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function CoffeeStore() {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href="/" legacyBehavior>
                    <a>Back to home</a>
                </Link>
                <Link href="/coffee-store/dynamic" legacyBehavior>
                    <a>go to dynamic page</a>
                </Link>
                <h1>Coffee Store page {router.query.id}</h1>
            </main>
        </>
    );
}
