import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import type { MouseEvent } from "react";
import Image from "next/image";

export default function Home() {
    const handleClick = (e: MouseEvent) => {
        e.preventDefault();
        console.log("You clicked the button!");
    };

    return (
        <>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText="View stores nearby"
                    buttonFunction={handleClick}
                />
                <Image
                    src="/static/hero-image.png"
                    width={700}
                    height={400}
                    alt="hero - girl with coffee sitting on clouds"
                    className={styles.heroImage}
                />
            </main>
        </>
    );
}
